# Generated by Django 5.0.1 on 2024-02-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_urlshort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='url_singkat',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
