# Generated by Django 5.0.1 on 2024-02-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_alter_urlshort_url_singkat'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshort',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
