# Generated by Django 5.0.1 on 2024-02-08 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_urlshort_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshort',
            name='jumlah_klik',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urlshort',
            name='waktu',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
