# Generated by Django 5.0.1 on 2024-02-12 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_urlshort_jumlah_klik_urlshort_waktu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_link', models.CharField(max_length=100, unique=True)),
                ('browser_link', models.CharField(max_length=100, unique=True)),
                ('device_link', models.CharField(max_length=100, unique=True)),
                ('urlshort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capstone.urlshort')),
            ],
        ),
    ]
